// <auto-generated />
using System;
using FS.Infrastructure.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FS.Infrastructure.Postgres.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260627182307_update_col_drop_duplicate")]
    partial class update_col_drop_duplicate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FS.Core.Entities.MediaAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AssetType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_key");

                    b.Property<string>("MediaStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("media_status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("asset_type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("MediaStatus", "CreatedAt");

                    b.ToTable("media_assets", (string)null);

                    b.HasDiscriminator<string>("asset_type").HasValue("MediaAsset");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("FS.Core.Entities.ImageAsset", b =>
                {
                    b.HasBaseType("FS.Core.Entities.MediaAsset");

                    b.HasDiscriminator().HasValue("image");
                });

            modelBuilder.Entity("FS.Core.Entities.MediaAsset", b =>
                {
                    b.OwnsOne("FS.Core.ValueObjects.MediaData", "MediaData", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId");

                            b1.Property<int>("ExpectedChunksCount")
                                .HasJsonPropertyName("expected_chunks_count");

                            b1.Property<long>("Size")
                                .HasJsonPropertyName("size");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("media_assets");

                            b1
                                .ToJson("media_data")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");

                            b1.OwnsOne("FS.Core.ValueObjects.ContentType", "ContentType", b2 =>
                                {
                                    b2.Property<Guid>("MediaDataMediaAssetId");

                                    b2.Property<string>("Category")
                                        .IsRequired()
                                        .HasJsonPropertyName("category");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasJsonPropertyName("value");

                                    b2.HasKey("MediaDataMediaAssetId");

                                    b2.ToTable("media_assets");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaDataMediaAssetId");
                                });

                            b1.OwnsOne("FS.Core.ValueObjects.FileName", "FileName", b2 =>
                                {
                                    b2.Property<Guid>("MediaDataMediaAssetId");

                                    b2.Property<string>("Extention")
                                        .IsRequired()
                                        .HasJsonPropertyName("extension");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasJsonPropertyName("name");

                                    b2.HasKey("MediaDataMediaAssetId");

                                    b2.ToTable("media_assets");

                                    b2.WithOwner()
                                        .HasForeignKey("MediaDataMediaAssetId");
                                });

                            b1.Navigation("ContentType")
                                .IsRequired();

                            b1.Navigation("FileName")
                                .IsRequired();
                        });

                    b.OwnsOne("FS.Core.ValueObjects.MediaOwner", "MediaOwner", b1 =>
                        {
                            b1.Property<Guid>("MediaAssetId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Context")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("owner_context");

                            b1.Property<Guid>("EntityId")
                                .HasColumnType("uuid")
                                .HasColumnName("owner_entity_id");

                            b1.HasKey("MediaAssetId");

                            b1.ToTable("media_assets");

                            b1.WithOwner()
                                .HasForeignKey("MediaAssetId");
                        });

                    b.Navigation("MediaData")
                        .IsRequired();

                    b.Navigation("MediaOwner")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
