export const mockLocations: LocationDTO[] = [
  {
    id: "loc_001",
    name: "Клиника на Тверской",
    address: {
      country: "Россия",
      region: "Москва",
      settlementName: "Москва",
      settlementType: "г.",
      street: "Тверская улица",
      buildingNumber: "12",
      buildingBlock: null,
      entrance: "2",
      floor: "3",
      premiseNumber: "305",
      premiseType: "офис",
      postCode: "125009",
      fullAddress:
        "г. Москва, Тверская улица, д. 12, подъезд 2, этаж 3, офис 305",
      comment: "Вход со двора, домофон 305",
    },
    timezone: "Europe/Moscow",
    isActive: true,
    createdAt: new Date("2023-02-10T09:00:00Z"),
    updatedAt: new Date("2024-11-05T14:32:00Z"),
  },
  {
    id: "loc_002",
    name: "Филиал на Невском",
    address: {
      country: "Россия",
      region: "Санкт-Петербург",
      settlementName: "Санкт-Петербург",
      settlementType: "г.",
      street: "Невский проспект",
      buildingNumber: "78",
      buildingBlock: "А",
      entrance: "1",
      floor: "2",
      premiseNumber: "14",
      premiseType: "помещение",
      postCode: "191025",
      fullAddress:
        "г. Санкт-Петербург, Невский проспект, д. 78, корп. А, этаж 2, пом. 14",
      comment: null,
    },
    timezone: "Europe/Moscow",
    isActive: true,
    createdAt: new Date("2023-05-18T09:00:00Z"),
    updatedAt: new Date("2025-01-20T11:10:00Z"),
  },
  {
    id: "loc_003",
    name: "Офис продаж Казань-Центр",
    address: {
      country: "Россия",
      region: "Республика Татарстан",
      settlementName: "Казань",
      settlementType: "г.",
      street: "улица Баумана",
      buildingNumber: "33",
      buildingBlock: null,
      entrance: "1",
      floor: "1",
      premiseNumber: "5",
      premiseType: "офис",
      postCode: "420111",
      fullAddress: "г. Казань, улица Баумана, д. 33, этаж 1, офис 5",
      comment: null,
    },
    timezone: "Europe/Moscow",
    isActive: true,
    createdAt: new Date("2023-09-02T09:00:00Z"),
    updatedAt: new Date("2024-08-14T16:45:00Z"),
  },
  {
    id: "loc_004",
    name: "Точка выдачи Новосибирск-Юг",
    address: {
      country: "Россия",
      region: "Новосибирская область",
      settlementName: "Новосибирск",
      settlementType: "г.",
      street: "улица Кирова",
      buildingNumber: "108",
      buildingBlock: "2",
      entrance: "3",
      floor: "1",
      premiseNumber: "1",
      premiseType: "помещение",
      postCode: "630090",
      fullAddress:
        "г. Новосибирск, улица Кирова, д. 108, корп. 2, подъезд 3, пом. 1",
      comment: "Закрыта на ремонт до 01.07.2026",
    },
    timezone: "Asia/Novosibirsk",
    isActive: false,
    createdAt: new Date("2022-11-30T09:00:00Z"),
    updatedAt: new Date("2026-05-01T10:00:00Z"),
  },
  {
    id: "loc_005",
    name: "Шоурум Екатеринбург",
    address: {
      country: "Россия",
      region: "Свердловская область",
      settlementName: "Екатеринбург",
      settlementType: "г.",
      street: "проспект Ленина",
      buildingNumber: "50",
      buildingBlock: null,
      entrance: "1",
      floor: "1",
      premiseNumber: "101",
      premiseType: "офис",
      postCode: "620075",
      fullAddress: "г. Екатеринбург, проспект Ленина, д. 50, этаж 1, офис 101",
      comment: null,
    },
    timezone: "Asia/Yekaterinburg",
    isActive: true,
    createdAt: new Date("2024-01-15T09:00:00Z"),
    updatedAt: new Date("2024-01-15T09:00:00Z"),
  },
  {
    id: "loc_006",
    name: "Минский филиал",
    address: {
      country: "Беларусь",
      region: "Минская область",
      settlementName: "Минск",
      settlementType: "г.",
      street: "проспект Независимости",
      buildingNumber: "95",
      buildingBlock: null,
      entrance: "1",
      floor: "4",
      premiseNumber: "412",
      premiseType: "офис",
      postCode: "220012",
      fullAddress: "г. Минск, проспект Независимости, д. 95, этаж 4, офис 412",
      comment: null,
    },
    timezone: "Europe/Minsk",
    isActive: true,
    createdAt: new Date("2023-07-21T09:00:00Z"),
    updatedAt: new Date("2025-03-11T08:20:00Z"),
  },
  {
    id: "loc_007",
    name: "Алматы Plaza",
    address: {
      country: "Казахстан",
      region: "Алматы",
      settlementName: "Алматы",
      settlementType: "г.",
      street: "улица Достык",
      buildingNumber: "117",
      buildingBlock: null,
      entrance: "2",
      floor: "6",
      premiseNumber: "603",
      premiseType: "офис",
      postCode: "050059",
      fullAddress:
        "г. Алматы, улица Достык, д. 117, подъезд 2, этаж 6, офис 603",
      comment: "Парковка во дворе бизнес-центра",
    },
    timezone: "Asia/Almaty",
    isActive: false,
    createdAt: new Date("2024-04-09T09:00:00Z"),
    updatedAt: new Date("2024-12-01T13:00:00Z"),
  },
];
