services:
  postgres:
    container_name: postgres
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ds_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
    ports:
      - 5435:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  seq:
    container_name: seq
    image: datalust/seq:latest
    ports:
      - "5341:5341"
      - "8080:80"
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    restart: always
    volumes:
      - seq-data:/data

volumes:
  postgres-data:
  seq-data:  
  